### ISSUE TITLE
Colors should follow GTK theme

### ISSUE THREAD

**Issue by bkanuka** [andialbrecht/runsqlrun#23]
I would have liked for this to take on the theme of the rest of my desktop. Honestly it's the main reason I tried to find a GTK SQL Client. RSR seems to be stuck to a dark theme.

**Comment by andialbrecht** [comment]
That's just a simple switch. Unfortunately I've had no time yet to provide
a proper preference UI. Maybe I could find a temporary workaround using
command line switches.

Bennett Kanuka <notifications@github.com> schrieb am Mo., 5. Dez. 2016
20:10:

**Comment by bkanuka** [comment]
Thanks looks great!

**Comment by andialbrecht** [comment]
FTR, I've just removed the (temporary) command line flag and added a preferences dialog with this option (and a few more).
